//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Adopcion_PGEntities : DbContext
    {
        public Adopcion_PGEntities()
            : base("name=Adopcion_PGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adoptante> adoptante { get; set; }
        public virtual DbSet<facilitador> facilitador { get; set; }
        public virtual DbSet<mascota> mascota { get; set; }
        public virtual DbSet<Seguimiento> Seguimiento { get; set; }
    
        public virtual int Actualizar_adoptante(string id_adoptante, string nom_adoptante, string cel_adoptante, string dir_adoptante, Nullable<int> ingresos_mensuales, Nullable<bool> activo)
        {
            var id_adoptanteParameter = id_adoptante != null ?
                new ObjectParameter("id_adoptante", id_adoptante) :
                new ObjectParameter("id_adoptante", typeof(string));
    
            var nom_adoptanteParameter = nom_adoptante != null ?
                new ObjectParameter("nom_adoptante", nom_adoptante) :
                new ObjectParameter("nom_adoptante", typeof(string));
    
            var cel_adoptanteParameter = cel_adoptante != null ?
                new ObjectParameter("cel_adoptante", cel_adoptante) :
                new ObjectParameter("cel_adoptante", typeof(string));
    
            var dir_adoptanteParameter = dir_adoptante != null ?
                new ObjectParameter("dir_adoptante", dir_adoptante) :
                new ObjectParameter("dir_adoptante", typeof(string));
    
            var ingresos_mensualesParameter = ingresos_mensuales.HasValue ?
                new ObjectParameter("ingresos_mensuales", ingresos_mensuales) :
                new ObjectParameter("ingresos_mensuales", typeof(int));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_adoptante", id_adoptanteParameter, nom_adoptanteParameter, cel_adoptanteParameter, dir_adoptanteParameter, ingresos_mensualesParameter, activoParameter);
        }
    
        public virtual int Actualizar_facilitador(string id_facilitador, string nom_facilitador, string cel_facilitador, string dir_facilitador, Nullable<bool> activo)
        {
            var id_facilitadorParameter = id_facilitador != null ?
                new ObjectParameter("id_facilitador", id_facilitador) :
                new ObjectParameter("id_facilitador", typeof(string));
    
            var nom_facilitadorParameter = nom_facilitador != null ?
                new ObjectParameter("nom_facilitador", nom_facilitador) :
                new ObjectParameter("nom_facilitador", typeof(string));
    
            var cel_facilitadorParameter = cel_facilitador != null ?
                new ObjectParameter("cel_facilitador", cel_facilitador) :
                new ObjectParameter("cel_facilitador", typeof(string));
    
            var dir_facilitadorParameter = dir_facilitador != null ?
                new ObjectParameter("dir_facilitador", dir_facilitador) :
                new ObjectParameter("dir_facilitador", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_facilitador", id_facilitadorParameter, nom_facilitadorParameter, cel_facilitadorParameter, dir_facilitadorParameter, activoParameter);
        }
    
        public virtual int Actualizar_mascota(string id_mascota, string especie, string genero, string nombre, Nullable<int> edad, string estado, string observaciones, Nullable<bool> activo)
        {
            var id_mascotaParameter = id_mascota != null ?
                new ObjectParameter("id_mascota", id_mascota) :
                new ObjectParameter("id_mascota", typeof(string));
    
            var especieParameter = especie != null ?
                new ObjectParameter("especie", especie) :
                new ObjectParameter("especie", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("genero", genero) :
                new ObjectParameter("genero", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var edadParameter = edad.HasValue ?
                new ObjectParameter("edad", edad) :
                new ObjectParameter("edad", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_mascota", id_mascotaParameter, especieParameter, generoParameter, nombreParameter, edadParameter, estadoParameter, observacionesParameter, activoParameter);
        }
    
        public virtual int Actualizar_seguimiento(string cod_seguimiento, Nullable<System.DateTime> fecha, string id_facilitador, string id_mascota, string id_adoptante, string estado_mascota, string observaciones, Nullable<bool> activo)
        {
            var cod_seguimientoParameter = cod_seguimiento != null ?
                new ObjectParameter("cod_seguimiento", cod_seguimiento) :
                new ObjectParameter("cod_seguimiento", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var id_facilitadorParameter = id_facilitador != null ?
                new ObjectParameter("id_facilitador", id_facilitador) :
                new ObjectParameter("id_facilitador", typeof(string));
    
            var id_mascotaParameter = id_mascota != null ?
                new ObjectParameter("id_mascota", id_mascota) :
                new ObjectParameter("id_mascota", typeof(string));
    
            var id_adoptanteParameter = id_adoptante != null ?
                new ObjectParameter("id_adoptante", id_adoptante) :
                new ObjectParameter("id_adoptante", typeof(string));
    
            var estado_mascotaParameter = estado_mascota != null ?
                new ObjectParameter("estado_mascota", estado_mascota) :
                new ObjectParameter("estado_mascota", typeof(string));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_seguimiento", cod_seguimientoParameter, fechaParameter, id_facilitadorParameter, id_mascotaParameter, id_adoptanteParameter, estado_mascotaParameter, observacionesParameter, activoParameter);
        }
    
        public virtual int Agregar_adoptante(string id_adoptante, string nom_adoptante, string cel_adoptante, string dir_adoptante, Nullable<int> ingresos_mensuales, Nullable<bool> activo)
        {
            var id_adoptanteParameter = id_adoptante != null ?
                new ObjectParameter("id_adoptante", id_adoptante) :
                new ObjectParameter("id_adoptante", typeof(string));
    
            var nom_adoptanteParameter = nom_adoptante != null ?
                new ObjectParameter("nom_adoptante", nom_adoptante) :
                new ObjectParameter("nom_adoptante", typeof(string));
    
            var cel_adoptanteParameter = cel_adoptante != null ?
                new ObjectParameter("cel_adoptante", cel_adoptante) :
                new ObjectParameter("cel_adoptante", typeof(string));
    
            var dir_adoptanteParameter = dir_adoptante != null ?
                new ObjectParameter("dir_adoptante", dir_adoptante) :
                new ObjectParameter("dir_adoptante", typeof(string));
    
            var ingresos_mensualesParameter = ingresos_mensuales.HasValue ?
                new ObjectParameter("ingresos_mensuales", ingresos_mensuales) :
                new ObjectParameter("ingresos_mensuales", typeof(int));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Agregar_adoptante", id_adoptanteParameter, nom_adoptanteParameter, cel_adoptanteParameter, dir_adoptanteParameter, ingresos_mensualesParameter, activoParameter);
        }
    
        public virtual int Agregar_facilitador(string id_facilitador, string nom_facilitador, string cel_facilitador, string dir_facilitador, Nullable<bool> activo)
        {
            var id_facilitadorParameter = id_facilitador != null ?
                new ObjectParameter("id_facilitador", id_facilitador) :
                new ObjectParameter("id_facilitador", typeof(string));
    
            var nom_facilitadorParameter = nom_facilitador != null ?
                new ObjectParameter("nom_facilitador", nom_facilitador) :
                new ObjectParameter("nom_facilitador", typeof(string));
    
            var cel_facilitadorParameter = cel_facilitador != null ?
                new ObjectParameter("cel_facilitador", cel_facilitador) :
                new ObjectParameter("cel_facilitador", typeof(string));
    
            var dir_facilitadorParameter = dir_facilitador != null ?
                new ObjectParameter("dir_facilitador", dir_facilitador) :
                new ObjectParameter("dir_facilitador", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Agregar_facilitador", id_facilitadorParameter, nom_facilitadorParameter, cel_facilitadorParameter, dir_facilitadorParameter, activoParameter);
        }
    
        public virtual int Agregar_mascota(string id_mascota, string especie, string genero, string nombre, Nullable<int> edad, string estado, string observaciones, Nullable<bool> activo)
        {
            var id_mascotaParameter = id_mascota != null ?
                new ObjectParameter("id_mascota", id_mascota) :
                new ObjectParameter("id_mascota", typeof(string));
    
            var especieParameter = especie != null ?
                new ObjectParameter("especie", especie) :
                new ObjectParameter("especie", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("genero", genero) :
                new ObjectParameter("genero", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var edadParameter = edad.HasValue ?
                new ObjectParameter("edad", edad) :
                new ObjectParameter("edad", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Agregar_mascota", id_mascotaParameter, especieParameter, generoParameter, nombreParameter, edadParameter, estadoParameter, observacionesParameter, activoParameter);
        }
    
        public virtual int Agregar_seguimiento(string cod_seguimiento, Nullable<System.DateTime> fecha, string id_facilitador, string id_mascota, string id_adoptante, string estado_mascota, string observaciones, Nullable<bool> activo)
        {
            var cod_seguimientoParameter = cod_seguimiento != null ?
                new ObjectParameter("cod_seguimiento", cod_seguimiento) :
                new ObjectParameter("cod_seguimiento", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var id_facilitadorParameter = id_facilitador != null ?
                new ObjectParameter("id_facilitador", id_facilitador) :
                new ObjectParameter("id_facilitador", typeof(string));
    
            var id_mascotaParameter = id_mascota != null ?
                new ObjectParameter("id_mascota", id_mascota) :
                new ObjectParameter("id_mascota", typeof(string));
    
            var id_adoptanteParameter = id_adoptante != null ?
                new ObjectParameter("id_adoptante", id_adoptante) :
                new ObjectParameter("id_adoptante", typeof(string));
    
            var estado_mascotaParameter = estado_mascota != null ?
                new ObjectParameter("estado_mascota", estado_mascota) :
                new ObjectParameter("estado_mascota", typeof(string));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Agregar_seguimiento", cod_seguimientoParameter, fechaParameter, id_facilitadorParameter, id_mascotaParameter, id_adoptanteParameter, estado_mascotaParameter, observacionesParameter, activoParameter);
        }
    
        public virtual int anula_adoptante(string aid_adoptante)
        {
            var aid_adoptanteParameter = aid_adoptante != null ?
                new ObjectParameter("aid_adoptante", aid_adoptante) :
                new ObjectParameter("aid_adoptante", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("anula_adoptante", aid_adoptanteParameter);
        }
    
        public virtual ObjectResult<consultar_adoptante_Result> consultar_adoptante(string cid_adoptante)
        {
            var cid_adoptanteParameter = cid_adoptante != null ?
                new ObjectParameter("cid_adoptante", cid_adoptante) :
                new ObjectParameter("cid_adoptante", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<consultar_adoptante_Result>("consultar_adoptante", cid_adoptanteParameter);
        }
    
        public virtual ObjectResult<consultar_facilitador_Result> consultar_facilitador(string cid_facilitador)
        {
            var cid_facilitadorParameter = cid_facilitador != null ?
                new ObjectParameter("cid_facilitador", cid_facilitador) :
                new ObjectParameter("cid_facilitador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<consultar_facilitador_Result>("consultar_facilitador", cid_facilitadorParameter);
        }
    
        public virtual ObjectResult<Consultar_mascota_Result> Consultar_mascota(string cid_mascota)
        {
            var cid_mascotaParameter = cid_mascota != null ?
                new ObjectParameter("cid_mascota", cid_mascota) :
                new ObjectParameter("cid_mascota", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consultar_mascota_Result>("Consultar_mascota", cid_mascotaParameter);
        }
    
        public virtual ObjectResult<Consultar_seguimiento_Result> Consultar_seguimiento(string cod_seguimiento)
        {
            var cod_seguimientoParameter = cod_seguimiento != null ?
                new ObjectParameter("cod_seguimiento", cod_seguimiento) :
                new ObjectParameter("cod_seguimiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consultar_seguimiento_Result>("Consultar_seguimiento", cod_seguimientoParameter);
        }
    
        public virtual int Eliminar_facilitador(string aid_facilitador)
        {
            var aid_facilitadorParameter = aid_facilitador != null ?
                new ObjectParameter("aid_facilitador", aid_facilitador) :
                new ObjectParameter("aid_facilitador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_facilitador", aid_facilitadorParameter);
        }
    
        public virtual int Eliminar_mascota(string aid_mascota)
        {
            var aid_mascotaParameter = aid_mascota != null ?
                new ObjectParameter("aid_mascota", aid_mascota) :
                new ObjectParameter("aid_mascota", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_mascota", aid_mascotaParameter);
        }
    
        public virtual int Eliminar_seguimiento(string cod_seguimiento)
        {
            var cod_seguimientoParameter = cod_seguimiento != null ?
                new ObjectParameter("cod_seguimiento", cod_seguimiento) :
                new ObjectParameter("cod_seguimiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eliminar_seguimiento", cod_seguimientoParameter);
        }
    }
}
