//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguimiento
    {
        public string cod_seguimiento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string id_facilitador { get; set; }
        public string id_mascota { get; set; }
        public string id_adoptante { get; set; }
        public string estado_mascota { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
